# yaml-language-server: $schema=../../schema/template_meta.schema.json

channels:
  schedule: 1276966864718925956
  events: 1276966894275920023
  introduction: 1276966938123309190
  general: 1276966967827501177
  forum: 1022659427758772365

default_timezone: Europe/Berlin

language_info:
  abbreviation: DGS
  native_localization: de
  localized_name:
    en: German Sign Language
    de: Deutsche Gebärdensprache

webhook:
  channel: schedule
  url: DGS_SCHEDULE_WEBHOOK_URL
