# yaml-language-server: $schema=../../schema/template_meta.schema.json

channels:
  schedule: 1276965747393953836
  events: 1276965778478075914
  introduction: 1276965818655047760
  general: 1276965857737576541
  forum: 1022659350797488138

default_timezone: Europe/Paris

language_info:
  abbreviation: LSF
  native_localization: fr
  localized_name:
    en: French Sign Language
    fr: Langue des signes française

webhook:
  channel: schedule
  url: LSF_SCHEDULE_WEBHOOK_URL
  message_id: LSF_SCHEDULE_MESSAGE_ID
