# yaml-language-server: $schema=../../schema/template_meta.schema.json

channels:
  schedule: 1276964936131674255
  events: 1276964968578941021
  introduction: 1276965012111491184
  general: 1276965052989181963
  forum: 1022656905547624569

default_timezone: America/New_York

language_info:
  abbreviation: ASL
  native_localization: en
  localized_name:
    en: American Sign Language
