# yaml-language-server: $schema=../../schema/template_meta.schema.json

channels:
  schedule: 771111584574603284
  events: 610999109910003722
  introduction: 552838791656636423
  general: 499435275844321282
  forum: 1085681642091315230

default_timezone: America/New_York

use_all_events: true

webhook:
  channel: schedule
  url: GLOBAL_SCHEDULE_WEBHOOK_URL
  message_id: GLOBAL_SCHEDULE_MESSAGE_ID
  header: |
    # Global Schedule

    This schedule shows a combined view of all the events in the server.
