name: "Build schedule manifests"

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch: {}

jobs:
  build_manifests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install requirements
        run: |
          pip install -U -r scripts/requirements.txt

      - name: Generate manifests
        run: |
          python scripts/build_manifests.py

      - name: Transfer manifests to deploy branch
        shell: bash
        run: |
          # Copy the manifests to a temporary directory
          export MANIFESTS_TEMP=$(mktemp -d)
          cp -r output/* $MANIFESTS_TEMP

          # Clear the repo so we can switch branches
          git clean -dfx

          # Switch branches to deploy
          git fetch origin deploy
          git checkout deploy

          # If the last commit was by GitHub Actions, revert it
          if [[ "$(git show -s --format='%ae' HEAD)" == *"github-actions"* ]]; then
            git reset --hard HEAD^;
          fi

          # Delete the output directory if it is there
          rm -rf output

          # Make a new output directory and put our generated artifacts there
          mkdir -p output
          cp -r ${MANIFESTS_TEMP}/* output

          # Upload the manifest
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "Autogenerated manifests created at $(date +%Y-%m-%d_%H-%M)"
          git push --force
